
name: seeknow_client
description: Flutter client for the SeekNow API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1

flutter:
  uses-material-design: true
